### ISSUE TITLE
Compilation errors

### ISSUE THREAD

**Issue by tseco15** [HesaiTechnology/HesaiLidar_ROS_2.0#6]
Hello, 
I am working with ROS2 Humble and Ubuntu 22.04.
Following the instructions for driver compilation, the compilation fails. There are some warnigns and finally errors.
You can find the output in the file attached.
Any suggestions?
[compilation_msgs_error.txt](https://github.com/HesaiTechnology/HesaiLidar_ROS_2.0/files/15429897/compilation_msgs_error.txt)

**Comment by jemmmel** [comment]
I am getting the same error using master branch, however issue seems to be with the SDK as the same issue occurs when building the SDK using cmake
[hesai_err.txt](https://github.com/user-attachments/files/15880604/hesai_err.txt)

**Comment by dholukeval** [comment]
> I am getting the same error using master branch, however issue seems to be with the SDK as the same issue occurs when building the SDK using cmake [hesai_err.txt](https://github.com/user-attachments/files/15880604/hesai_err.txt)

I am facing the same problem. I can not build the Hesai SDK nor Hesai ros driver as it is dependent on SDK. Did you find the solution?

**Comment by jemmmel** [comment]
Since we are not using CUDA we simply removed it from the CMakeLists
